[Hunspell]
lang = "en_US"

search_dirs = []

# relative to this configuration file or absolute paths
extra_dictonaries = ["./.config/topic.dic"]

[Hunspell.quirks]
# transforms words that are provided by the tokenizer
# into word fragments based on the capture groups which are to be checked.
# If no capture groups are present, the matched word is whitelisted.
transform_regex = ["^'([^\\s])'$", "^[0-9]+x$"]
# accepts `alphabeta` variants if the checker provides a replacement suggestion
# of `alpha-beta`.
allow_concatenation = true
# and the counterpart, which accepts words with dashes, when the suggestion has
# recommendations without the dashes. This is less common.
allow_dashed = false